# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='policy_expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
