# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20180829_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='policy_number',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
