version: "3"

services:
    db:
      image: postgres
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_DB=postgres
          - POSTGRES_PWD=!@#Postgres!@#
      volumes:
        - .postgres_data:/var/lib/postgresql/data/
    web:
        build: .
        command: python /code/insurance/manage.py migrate
        command: python /code/insurance/manage.py runserver 0.0.0.0:8009
        volumes:
            - .:/code
        ports:
            - "8009:8009"
        depends_on:
            - db
