# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_agent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_number',
            field=models.CharField(max_length=25),
        ),
    ]
